
export const CART_ITEMS_TOTAL_PRICE = 'CART_ITEMS_TOTAL_PRICE';
export const CART_ITEMS = 'CART_ITEMS';
export const IS_PRODUCT_IN_THE_CART = 'IS_PRODUCT_IN_THE_CART';
export const IS_PRODUCT_LIKED = 'IS_PRODUCT_LIKED';
export const LIKED_GOODS_COUNT = 'LIKED_GOODS_COUNT';
