export const ADD_PRODUCT_TO_LIKED = 'ADD_PRODUCT_TO_LIKED';
export const REMOVE_PRODUCT_FROM_LIKED = 'REMOVE_PRODUCT_FROM_LIKED';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';