export const GALLERY_POPULAR_GOODS = 'GALLERY_POPULAR_GOODS';
export const GALLERY_POPULAR_GOODS_MAIN_IMAGE = 'GALLERY_POPULAR_GOODS_MAIN_IMAGE';
export const GALLERY_LATEST_GOODS = 'GALLERY_LATEST_GOODS';
export const GALLERY_LATEST_GOODS_MAIN_IMAGE = 'GALLERY_LATEST_GOODS_MAIN_IMAGE';