export const UPDATE_POPULAR_GOODS = 'UPDATE_POPULAR_GOODS';
export const UPDATE_POPULAR_GOODS_MAIN_IMAGE = 'UPDATE_POPULAR_GOODS_MAIN_IMAGE';
export const UPDATE_LATEST_GOODS = 'UPDATE_LATEST_GOODS';
export const UPDATE_LATEST_GOODS_MAIN_IMAGE = 'UPDATE_LATEST_GOODS_MAIN_IMAGE';